<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Company>Cedric-Belin.fr</Company>
		<Copyright>© Cédric Belin</Copyright>
		<Description>Prevent comment spam using the Akismet service.</Description>
		<Product>Akismet for F#</Product>
		<Version>1.0.0</Version>
	</PropertyGroup>

	<PropertyGroup>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AssemblyName>Belin.Akismet.Tests</AssemblyName>
		<BaseOutputPath>obj</BaseOutputPath>
		<OutDir>../Binaries</OutDir>
		<RootNamespace>Belin.Akismet</RootNamespace>
		<SatelliteResourceLanguages>en</SatelliteResourceLanguages>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MSTest" Version="4.*" />
		<ProjectReference Include="../Sources/Akismet.fsproj" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="AssemblyInfo.fs" />
		<Compile Include="Blog.Tests.fs" />
	</ItemGroup>
</Project>
